name: CI

on:
  push:
    branches: main
  pull_request:
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: Run linter
      run: crystal tool format --check
