name: CI

on:
  push:
    branches: main
  pull_request:
permissions:
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: latest

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: shards install

      - name: Run linter
        run: make lint

      - name: Build extension
        run: make extension
      
      - name: Build example
        run: make check

      - name: Run specs
        run: make specs
